version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"

# Install regular dependencies.
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
